github:
  - likhonsheikhcodes
  - RecentCoder
  - Rekt-Developer
  - scripters-store
ko_fi: https://buymeacoffee.com/flashusdtsendersoftware
custom:
  - url: https://flashusdtsender.xyz/
    description: "Support the FlashUSDT Sender project through our official website."
