funding_goods:
  - title: "GitHub Sponsors"
    description: "Support the project on GitHub Sponsors. Contributions directly help with development and infrastructure."
    platform: github
    benefits:
      - "Exclusive project updates"
      - "Early access to new features"
      - "Priority support"
  
  - title: "Buy Me A Coffee"
    description: "Support the project with a small donation on Buy Me A Coffee."
    platform: ko_fi
    benefits:
      - "Thank you shoutout"
      - "Access to donor-only content"
  
  - title: "Thanks.dev"
    description: "Contribute via Thanks.dev to help improve the project."
    platform: thanks_dev
    benefits:
      - "Recognition on the project page"
      - "Thank you message"
  
  - title: "Custom FlashUSDT Support"
    description: "Support the project directly via the FlashUSDT platform."
    platform: FlashUSDT
    benefits:
      - "Special mentions in project updates"
      - "Direct communication with the development team"
