name: Daily Work

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          mkdir -p contributors
          echo "Commit made at $(date '+%Y-%m-%d %H:%M:%S')" > contributors/log.txt

      - name: Pull latest changes
        run: git pull

      - name: Commit and Push for Random Users
        run: |
          # Function to generate a random email and username
          generate_random_user() {
            local random_username="user$(shuf -i 1000-9999 -n 1)"
            local random_email="${random_username}@example.com"
            echo "$random_email:$random_username"
          }

          # Generate random users and commit
          for i in {1..10}; do
            user=$(generate_random_user)
            email="${user%%:*}"
            name="${user##*:}"
            
            echo "Processing random user: $name <$email>"
            
            # Set Git user details globally
            git config --global user.email "$email"
            git config --global user.name "$name"
            
            # Make the changes for the user
            log_file="contributors/log_${name// /_}.txt"
            echo "Commit at $(date '+%Y-%m-%d %H:%M:%S')" > "$log_file"
            
            # Stage and commit the changes
            git add "$log_file"
            
            # Commit if there are changes to commit
            if git diff --cached --quiet; then
              echo "No changes to commit for $name"
            else
              git commit -m "Daily update at $(date '+%Y-%m-%d %H:%M:%S')"
              git push
              echo "Changes pushed for $name"
            fi
          done
