name: Daily Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Latest Changes
        run: git pull origin main  # Ensure you are pulling the latest changes from the main branch

      - name: Fetch Random Users
        id: fetch_users
        run: |
          users_json=$(curl -s 'https://randomuser.me/api/?results=30&nat=us')  # Fetch 30 random users
          echo "$users_json" > users.json

      - name: Parse and Commit for Users
        run: |
          # Parse the users data and loop through each user
          users=$(jq -r '.results[] | "
